# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 06:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=150, verbose_name='회의 이름')),
                ('time', models.CharField(max_length=100, verbose_name='회의 날짜')),
                ('location', models.CharField(max_length=150, verbose_name='회의 장소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user_name', models.CharField(default='', max_length=30, verbose_name='참석자 이름')),
                ('is_participate', models.BooleanField(default=False, verbose_name='참석 여부')),
                ('participate_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='참석한 시간')),
                ('minutes', models.TextField(default='회의록을 적어주세요', max_length=500, verbose_name='회의')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('custom_pk', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_meeting', to='meetings.Meeting', verbose_name='meeting PK')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_user', to=settings.AUTH_USER_MODEL, verbose_name='user PK')),
            ],
        ),
    ]
