# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user_name',
        ),
    ]
