# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 06:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commute',
            fields=[
                ('is_in', models.BooleanField(default=False, verbose_name='출근 여부')),
                ('is_out', models.BooleanField(default=False, verbose_name='퇴근 여부')),
                ('in_time', models.CharField(blank=True, default=datetime.datetime.now, max_length=30, verbose_name='출근 시간')),
                ('out_time', models.CharField(blank=True, default=datetime.datetime.now, max_length=30, verbose_name='퇴근 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('shift', models.CharField(default='', max_length=50, verbose_name='근무 시간')),
                ('custom_pk', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commute_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
