# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commute',
            name='in_time',
            field=models.DateTimeField(blank=True, max_length=30, verbose_name='출근 시간'),
        ),
        migrations.AlterField(
            model_name='commute',
            name='out_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, max_length=30, verbose_name='퇴근 시간'),
        ),
    ]
